// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_CGS_HashtagLDA
void rcpp_CGS_HashtagLDA(IntegerMatrix w, IntegerMatrix h, IntegerVector doc_users, NumericVector alphastar, NumericVector betaV, NumericVector betaH, NumericVector bH, int iterations, int TOPICS, int U, int D, int V, int H, IntegerVector N, IntegerVector L, std::string result_folder);
RcppExport SEXP _mdtm_rcpp_CGS_HashtagLDA(SEXP wSEXP, SEXP hSEXP, SEXP doc_usersSEXP, SEXP alphastarSEXP, SEXP betaVSEXP, SEXP betaHSEXP, SEXP bHSEXP, SEXP iterationsSEXP, SEXP TOPICSSEXP, SEXP USEXP, SEXP DSEXP, SEXP VSEXP, SEXP HSEXP, SEXP NSEXP, SEXP LSEXP, SEXP result_folderSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type w(wSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type h(hSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type doc_users(doc_usersSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alphastar(alphastarSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type betaV(betaVSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type betaH(betaHSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bH(bHSEXP);
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< int >::type TOPICS(TOPICSSEXP);
    Rcpp::traits::input_parameter< int >::type U(USEXP);
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    Rcpp::traits::input_parameter< int >::type V(VSEXP);
    Rcpp::traits::input_parameter< int >::type H(HSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type N(NSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type L(LSEXP);
    Rcpp::traits::input_parameter< std::string >::type result_folder(result_folderSEXP);
    rcpp_CGS_HashtagLDA(w, h, doc_users, alphastar, betaV, betaH, bH, iterations, TOPICS, U, D, V, H, N, L, result_folder);
    return R_NilValue;
END_RCPP
}
// pred_single_HashtagLDA
void pred_single_HashtagLDA(IntegerMatrix w, IntegerMatrix h, IntegerVector doc_users, NumericVector alphastar, NumericVector betaV, NumericVector betaH, NumericVector bH, int iterations, int TOPICS, int U, int D, int V, int H, IntegerVector N, IntegerVector L, int L_sum, NumericMatrix WY1ZX, NumericMatrix HY1ZX, NumericMatrix Zstar, double Yh1, NumericVector HY0, std::string result_folder);
RcppExport SEXP _mdtm_pred_single_HashtagLDA(SEXP wSEXP, SEXP hSEXP, SEXP doc_usersSEXP, SEXP alphastarSEXP, SEXP betaVSEXP, SEXP betaHSEXP, SEXP bHSEXP, SEXP iterationsSEXP, SEXP TOPICSSEXP, SEXP USEXP, SEXP DSEXP, SEXP VSEXP, SEXP HSEXP, SEXP NSEXP, SEXP LSEXP, SEXP L_sumSEXP, SEXP WY1ZXSEXP, SEXP HY1ZXSEXP, SEXP ZstarSEXP, SEXP Yh1SEXP, SEXP HY0SEXP, SEXP result_folderSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type w(wSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type h(hSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type doc_users(doc_usersSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alphastar(alphastarSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type betaV(betaVSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type betaH(betaHSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bH(bHSEXP);
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< int >::type TOPICS(TOPICSSEXP);
    Rcpp::traits::input_parameter< int >::type U(USEXP);
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    Rcpp::traits::input_parameter< int >::type V(VSEXP);
    Rcpp::traits::input_parameter< int >::type H(HSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type N(NSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type L(LSEXP);
    Rcpp::traits::input_parameter< int >::type L_sum(L_sumSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type WY1ZX(WY1ZXSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type HY1ZX(HY1ZXSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Zstar(ZstarSEXP);
    Rcpp::traits::input_parameter< double >::type Yh1(Yh1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type HY0(HY0SEXP);
    Rcpp::traits::input_parameter< std::string >::type result_folder(result_folderSEXP);
    pred_single_HashtagLDA(w, h, doc_users, alphastar, betaV, betaH, bH, iterations, TOPICS, U, D, V, H, N, L, L_sum, WY1ZX, HY1ZX, Zstar, Yh1, HY0, result_folder);
    return R_NilValue;
END_RCPP
}
// pred_all_HashtagLDA
void pred_all_HashtagLDA(IntegerMatrix w, IntegerMatrix h, IntegerVector doc_users, NumericVector alphastar, NumericVector betaV, NumericVector betaH, NumericVector bH, int iterations, int TOPICS, int U, int D, int V, int H, IntegerVector N, IntegerVector L, int L_sum, NumericMatrix WY1ZX, NumericMatrix HY1ZX, NumericMatrix Zstar, double Yh1, NumericVector HY0, std::string result_folder);
RcppExport SEXP _mdtm_pred_all_HashtagLDA(SEXP wSEXP, SEXP hSEXP, SEXP doc_usersSEXP, SEXP alphastarSEXP, SEXP betaVSEXP, SEXP betaHSEXP, SEXP bHSEXP, SEXP iterationsSEXP, SEXP TOPICSSEXP, SEXP USEXP, SEXP DSEXP, SEXP VSEXP, SEXP HSEXP, SEXP NSEXP, SEXP LSEXP, SEXP L_sumSEXP, SEXP WY1ZXSEXP, SEXP HY1ZXSEXP, SEXP ZstarSEXP, SEXP Yh1SEXP, SEXP HY0SEXP, SEXP result_folderSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type w(wSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type h(hSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type doc_users(doc_usersSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alphastar(alphastarSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type betaV(betaVSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type betaH(betaHSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bH(bHSEXP);
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< int >::type TOPICS(TOPICSSEXP);
    Rcpp::traits::input_parameter< int >::type U(USEXP);
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    Rcpp::traits::input_parameter< int >::type V(VSEXP);
    Rcpp::traits::input_parameter< int >::type H(HSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type N(NSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type L(LSEXP);
    Rcpp::traits::input_parameter< int >::type L_sum(L_sumSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type WY1ZX(WY1ZXSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type HY1ZX(HY1ZXSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Zstar(ZstarSEXP);
    Rcpp::traits::input_parameter< double >::type Yh1(Yh1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type HY0(HY0SEXP);
    Rcpp::traits::input_parameter< std::string >::type result_folder(result_folderSEXP);
    pred_all_HashtagLDA(w, h, doc_users, alphastar, betaV, betaH, bH, iterations, TOPICS, U, D, V, H, N, L, L_sum, WY1ZX, HY1ZX, Zstar, Yh1, HY0, result_folder);
    return R_NilValue;
END_RCPP
}
// rcpp_CGS_LDA
void rcpp_CGS_LDA(IntegerMatrix w, NumericVector alpha, NumericVector betaV, int iterations, int TOPICS, int D, int V, IntegerVector N, std::string result_folder);
RcppExport SEXP _mdtm_rcpp_CGS_LDA(SEXP wSEXP, SEXP alphaSEXP, SEXP betaVSEXP, SEXP iterationsSEXP, SEXP TOPICSSEXP, SEXP DSEXP, SEXP VSEXP, SEXP NSEXP, SEXP result_folderSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type w(wSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type betaV(betaVSEXP);
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< int >::type TOPICS(TOPICSSEXP);
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    Rcpp::traits::input_parameter< int >::type V(VSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type N(NSEXP);
    Rcpp::traits::input_parameter< std::string >::type result_folder(result_folderSEXP);
    rcpp_CGS_LDA(w, alpha, betaV, iterations, TOPICS, D, V, N, result_folder);
    return R_NilValue;
END_RCPP
}
// pred_single_LDA
void pred_single_LDA(IntegerMatrix w, NumericVector alpha, NumericVector betaV, int iterations, int TOPICS, int D, int V, IntegerVector N, NumericMatrix WY1ZX, std::string result_folder);
RcppExport SEXP _mdtm_pred_single_LDA(SEXP wSEXP, SEXP alphaSEXP, SEXP betaVSEXP, SEXP iterationsSEXP, SEXP TOPICSSEXP, SEXP DSEXP, SEXP VSEXP, SEXP NSEXP, SEXP WY1ZXSEXP, SEXP result_folderSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type w(wSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type betaV(betaVSEXP);
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< int >::type TOPICS(TOPICSSEXP);
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    Rcpp::traits::input_parameter< int >::type V(VSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type N(NSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type WY1ZX(WY1ZXSEXP);
    Rcpp::traits::input_parameter< std::string >::type result_folder(result_folderSEXP);
    pred_single_LDA(w, alpha, betaV, iterations, TOPICS, D, V, N, WY1ZX, result_folder);
    return R_NilValue;
END_RCPP
}
// pred_all_LDA
void pred_all_LDA(IntegerMatrix w, NumericVector alpha, NumericVector betaV, int iterations, int TOPICS, int D, int V, IntegerVector N, NumericMatrix WY1ZX, std::string result_folder);
RcppExport SEXP _mdtm_pred_all_LDA(SEXP wSEXP, SEXP alphaSEXP, SEXP betaVSEXP, SEXP iterationsSEXP, SEXP TOPICSSEXP, SEXP DSEXP, SEXP VSEXP, SEXP NSEXP, SEXP WY1ZXSEXP, SEXP result_folderSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type w(wSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type betaV(betaVSEXP);
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< int >::type TOPICS(TOPICSSEXP);
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    Rcpp::traits::input_parameter< int >::type V(VSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type N(NSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type WY1ZX(WY1ZXSEXP);
    Rcpp::traits::input_parameter< std::string >::type result_folder(result_folderSEXP);
    pred_all_LDA(w, alpha, betaV, iterations, TOPICS, D, V, N, WY1ZX, result_folder);
    return R_NilValue;
END_RCPP
}
// rcpp_CGS_MicroblogLDA
void rcpp_CGS_MicroblogLDA(std::vector<NumericMatrix> w, IntegerVector doc_users, NumericVector alphastar, NumericVector alpha, std::vector<NumericVector> beta, NumericMatrix b, NumericVector bdelta, NumericVector bT, double alpha0, int iterations, int TOPICS, int K, int U, int D, IntegerVector V, IntegerMatrix N, IntegerVector Dusers, std::string result_folder);
RcppExport SEXP _mdtm_rcpp_CGS_MicroblogLDA(SEXP wSEXP, SEXP doc_usersSEXP, SEXP alphastarSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP bSEXP, SEXP bdeltaSEXP, SEXP bTSEXP, SEXP alpha0SEXP, SEXP iterationsSEXP, SEXP TOPICSSEXP, SEXP KSEXP, SEXP USEXP, SEXP DSEXP, SEXP VSEXP, SEXP NSEXP, SEXP DusersSEXP, SEXP result_folderSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<NumericMatrix> >::type w(wSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type doc_users(doc_usersSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alphastar(alphastarSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< std::vector<NumericVector> >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bdelta(bdeltaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bT(bTSEXP);
    Rcpp::traits::input_parameter< double >::type alpha0(alpha0SEXP);
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< int >::type TOPICS(TOPICSSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type U(USEXP);
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type V(VSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type N(NSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Dusers(DusersSEXP);
    Rcpp::traits::input_parameter< std::string >::type result_folder(result_folderSEXP);
    rcpp_CGS_MicroblogLDA(w, doc_users, alphastar, alpha, beta, b, bdelta, bT, alpha0, iterations, TOPICS, K, U, D, V, N, Dusers, result_folder);
    return R_NilValue;
END_RCPP
}
// pred_single_MicroblogLDA
void pred_single_MicroblogLDA(std::vector<NumericMatrix>& w, IntegerVector doc_users, NumericVector alphastar, NumericVector alpha, std::vector<NumericVector>& beta, NumericMatrix b, NumericVector bdelta, NumericVector bT, double alpha0, int iterations, int TOPICS, int K, int U, int D, IntegerVector V, IntegerMatrix N, NumericVector N_sum, IntegerVector Dusers, NumericVector& X1, NumericMatrix& Zstar, double& LAMBDA1, NumericVector& Yv1, std::vector<NumericMatrix>& WY1ZX, std::vector<NumericVector>& WY0, std::string result_folder);
RcppExport SEXP _mdtm_pred_single_MicroblogLDA(SEXP wSEXP, SEXP doc_usersSEXP, SEXP alphastarSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP bSEXP, SEXP bdeltaSEXP, SEXP bTSEXP, SEXP alpha0SEXP, SEXP iterationsSEXP, SEXP TOPICSSEXP, SEXP KSEXP, SEXP USEXP, SEXP DSEXP, SEXP VSEXP, SEXP NSEXP, SEXP N_sumSEXP, SEXP DusersSEXP, SEXP X1SEXP, SEXP ZstarSEXP, SEXP LAMBDA1SEXP, SEXP Yv1SEXP, SEXP WY1ZXSEXP, SEXP WY0SEXP, SEXP result_folderSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<NumericMatrix>& >::type w(wSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type doc_users(doc_usersSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alphastar(alphastarSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< std::vector<NumericVector>& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bdelta(bdeltaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bT(bTSEXP);
    Rcpp::traits::input_parameter< double >::type alpha0(alpha0SEXP);
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< int >::type TOPICS(TOPICSSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type U(USEXP);
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type V(VSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type N(NSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type N_sum(N_sumSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Dusers(DusersSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type Zstar(ZstarSEXP);
    Rcpp::traits::input_parameter< double& >::type LAMBDA1(LAMBDA1SEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type Yv1(Yv1SEXP);
    Rcpp::traits::input_parameter< std::vector<NumericMatrix>& >::type WY1ZX(WY1ZXSEXP);
    Rcpp::traits::input_parameter< std::vector<NumericVector>& >::type WY0(WY0SEXP);
    Rcpp::traits::input_parameter< std::string >::type result_folder(result_folderSEXP);
    pred_single_MicroblogLDA(w, doc_users, alphastar, alpha, beta, b, bdelta, bT, alpha0, iterations, TOPICS, K, U, D, V, N, N_sum, Dusers, X1, Zstar, LAMBDA1, Yv1, WY1ZX, WY0, result_folder);
    return R_NilValue;
END_RCPP
}
// pred_all_MicroblogLDA
void pred_all_MicroblogLDA(std::vector<NumericMatrix>& w, IntegerVector doc_users, NumericVector alphastar, NumericVector alpha, std::vector<NumericVector>& beta, NumericMatrix b, NumericVector bdelta, NumericVector bT, double alpha0, int iterations, int TOPICS, int K, int U, int D, IntegerVector V, IntegerMatrix N, NumericVector N_sum, IntegerVector Dusers, NumericVector& X1, NumericMatrix& Zstar, double& LAMBDA1, NumericVector& Yv1, std::vector<NumericMatrix>& WY1ZX, std::vector<NumericVector>& WY0, std::string result_folder);
RcppExport SEXP _mdtm_pred_all_MicroblogLDA(SEXP wSEXP, SEXP doc_usersSEXP, SEXP alphastarSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP bSEXP, SEXP bdeltaSEXP, SEXP bTSEXP, SEXP alpha0SEXP, SEXP iterationsSEXP, SEXP TOPICSSEXP, SEXP KSEXP, SEXP USEXP, SEXP DSEXP, SEXP VSEXP, SEXP NSEXP, SEXP N_sumSEXP, SEXP DusersSEXP, SEXP X1SEXP, SEXP ZstarSEXP, SEXP LAMBDA1SEXP, SEXP Yv1SEXP, SEXP WY1ZXSEXP, SEXP WY0SEXP, SEXP result_folderSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<NumericMatrix>& >::type w(wSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type doc_users(doc_usersSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alphastar(alphastarSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< std::vector<NumericVector>& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bdelta(bdeltaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bT(bTSEXP);
    Rcpp::traits::input_parameter< double >::type alpha0(alpha0SEXP);
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< int >::type TOPICS(TOPICSSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type U(USEXP);
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type V(VSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type N(NSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type N_sum(N_sumSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Dusers(DusersSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type Zstar(ZstarSEXP);
    Rcpp::traits::input_parameter< double& >::type LAMBDA1(LAMBDA1SEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type Yv1(Yv1SEXP);
    Rcpp::traits::input_parameter< std::vector<NumericMatrix>& >::type WY1ZX(WY1ZXSEXP);
    Rcpp::traits::input_parameter< std::vector<NumericVector>& >::type WY0(WY0SEXP);
    Rcpp::traits::input_parameter< std::string >::type result_folder(result_folderSEXP);
    pred_all_MicroblogLDA(w, doc_users, alphastar, alpha, beta, b, bdelta, bT, alpha0, iterations, TOPICS, K, U, D, V, N, N_sum, Dusers, X1, Zstar, LAMBDA1, Yv1, WY1ZX, WY0, result_folder);
    return R_NilValue;
END_RCPP
}
// rcpp_CGS_TwitterLDA
void rcpp_CGS_TwitterLDA(IntegerMatrix w, IntegerVector doc_users, NumericVector alphastar, NumericVector betaV, NumericVector bV, int iterations, int TOPICS, int U, int D, int V, IntegerVector N, std::string result_folder);
RcppExport SEXP _mdtm_rcpp_CGS_TwitterLDA(SEXP wSEXP, SEXP doc_usersSEXP, SEXP alphastarSEXP, SEXP betaVSEXP, SEXP bVSEXP, SEXP iterationsSEXP, SEXP TOPICSSEXP, SEXP USEXP, SEXP DSEXP, SEXP VSEXP, SEXP NSEXP, SEXP result_folderSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type w(wSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type doc_users(doc_usersSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alphastar(alphastarSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type betaV(betaVSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bV(bVSEXP);
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< int >::type TOPICS(TOPICSSEXP);
    Rcpp::traits::input_parameter< int >::type U(USEXP);
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    Rcpp::traits::input_parameter< int >::type V(VSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type N(NSEXP);
    Rcpp::traits::input_parameter< std::string >::type result_folder(result_folderSEXP);
    rcpp_CGS_TwitterLDA(w, doc_users, alphastar, betaV, bV, iterations, TOPICS, U, D, V, N, result_folder);
    return R_NilValue;
END_RCPP
}
// pred_single_TwitterLDA
void pred_single_TwitterLDA(IntegerMatrix w, IntegerVector doc_users, NumericVector alphastar, NumericVector betaV, NumericVector bV, int iterations, int TOPICS, int U, int D, int V, IntegerVector N, int N_sum, NumericMatrix WY1ZX, NumericMatrix Zstar, double Yv1, NumericVector WY0, std::string result_folder);
RcppExport SEXP _mdtm_pred_single_TwitterLDA(SEXP wSEXP, SEXP doc_usersSEXP, SEXP alphastarSEXP, SEXP betaVSEXP, SEXP bVSEXP, SEXP iterationsSEXP, SEXP TOPICSSEXP, SEXP USEXP, SEXP DSEXP, SEXP VSEXP, SEXP NSEXP, SEXP N_sumSEXP, SEXP WY1ZXSEXP, SEXP ZstarSEXP, SEXP Yv1SEXP, SEXP WY0SEXP, SEXP result_folderSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type w(wSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type doc_users(doc_usersSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alphastar(alphastarSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type betaV(betaVSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bV(bVSEXP);
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< int >::type TOPICS(TOPICSSEXP);
    Rcpp::traits::input_parameter< int >::type U(USEXP);
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    Rcpp::traits::input_parameter< int >::type V(VSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type N_sum(N_sumSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type WY1ZX(WY1ZXSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Zstar(ZstarSEXP);
    Rcpp::traits::input_parameter< double >::type Yv1(Yv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type WY0(WY0SEXP);
    Rcpp::traits::input_parameter< std::string >::type result_folder(result_folderSEXP);
    pred_single_TwitterLDA(w, doc_users, alphastar, betaV, bV, iterations, TOPICS, U, D, V, N, N_sum, WY1ZX, Zstar, Yv1, WY0, result_folder);
    return R_NilValue;
END_RCPP
}
// pred_all_TwitterLDA
void pred_all_TwitterLDA(IntegerMatrix w, IntegerVector doc_users, NumericVector alphastar, NumericVector betaV, NumericVector bV, int iterations, int TOPICS, int U, int D, int V, IntegerVector N, int N_sum, NumericMatrix WY1ZX, NumericMatrix Zstar, double Yv1, NumericVector WY0, std::string result_folder);
RcppExport SEXP _mdtm_pred_all_TwitterLDA(SEXP wSEXP, SEXP doc_usersSEXP, SEXP alphastarSEXP, SEXP betaVSEXP, SEXP bVSEXP, SEXP iterationsSEXP, SEXP TOPICSSEXP, SEXP USEXP, SEXP DSEXP, SEXP VSEXP, SEXP NSEXP, SEXP N_sumSEXP, SEXP WY1ZXSEXP, SEXP ZstarSEXP, SEXP Yv1SEXP, SEXP WY0SEXP, SEXP result_folderSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type w(wSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type doc_users(doc_usersSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alphastar(alphastarSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type betaV(betaVSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bV(bVSEXP);
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< int >::type TOPICS(TOPICSSEXP);
    Rcpp::traits::input_parameter< int >::type U(USEXP);
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    Rcpp::traits::input_parameter< int >::type V(VSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type N_sum(N_sumSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type WY1ZX(WY1ZXSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Zstar(ZstarSEXP);
    Rcpp::traits::input_parameter< double >::type Yv1(Yv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type WY0(WY0SEXP);
    Rcpp::traits::input_parameter< std::string >::type result_folder(result_folderSEXP);
    pred_all_TwitterLDA(w, doc_users, alphastar, betaV, bV, iterations, TOPICS, U, D, V, N, N_sum, WY1ZX, Zstar, Yv1, WY0, result_folder);
    return R_NilValue;
END_RCPP
}
// rcpp_CGS_clickbaitLDA
void rcpp_CGS_clickbaitLDA(IntegerMatrix w, IntegerVector x, double alphastar, double betaV, NumericVector betaB, NumericVector b_doc, NumericMatrix b_back, int iterations, int TOPICS, int D, int Dt, int V, IntegerVector N, std::string result_folder);
RcppExport SEXP _mdtm_rcpp_CGS_clickbaitLDA(SEXP wSEXP, SEXP xSEXP, SEXP alphastarSEXP, SEXP betaVSEXP, SEXP betaBSEXP, SEXP b_docSEXP, SEXP b_backSEXP, SEXP iterationsSEXP, SEXP TOPICSSEXP, SEXP DSEXP, SEXP DtSEXP, SEXP VSEXP, SEXP NSEXP, SEXP result_folderSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type w(wSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type alphastar(alphastarSEXP);
    Rcpp::traits::input_parameter< double >::type betaV(betaVSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type betaB(betaBSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b_doc(b_docSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type b_back(b_backSEXP);
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< int >::type TOPICS(TOPICSSEXP);
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    Rcpp::traits::input_parameter< int >::type Dt(DtSEXP);
    Rcpp::traits::input_parameter< int >::type V(VSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type N(NSEXP);
    Rcpp::traits::input_parameter< std::string >::type result_folder(result_folderSEXP);
    rcpp_CGS_clickbaitLDA(w, x, alphastar, betaV, betaB, b_doc, b_back, iterations, TOPICS, D, Dt, V, N, result_folder);
    return R_NilValue;
END_RCPP
}
// update_counts_LDA
void update_counts_LDA(IntegerMatrix w, NumericVector alpha, int TOPICS, int D, IntegerVector N, IntegerMatrix& zV, NumericMatrix& WY1ZX, NumericMatrix& Z, bool update_state);
RcppExport SEXP _mdtm_update_counts_LDA(SEXP wSEXP, SEXP alphaSEXP, SEXP TOPICSSEXP, SEXP DSEXP, SEXP NSEXP, SEXP zVSEXP, SEXP WY1ZXSEXP, SEXP ZSEXP, SEXP update_stateSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type w(wSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type TOPICS(TOPICSSEXP);
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type N(NSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix& >::type zV(zVSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type WY1ZX(WY1ZXSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< bool >::type update_state(update_stateSEXP);
    update_counts_LDA(w, alpha, TOPICS, D, N, zV, WY1ZX, Z, update_state);
    return R_NilValue;
END_RCPP
}
// update_counts_TwitterLDA
void update_counts_TwitterLDA(IntegerMatrix w, IntegerVector doc_users, NumericVector alphastar, NumericVector bV, int TOPICS, int D, IntegerVector N, IntegerVector& zstar, IntegerMatrix& yV, NumericMatrix& WY1ZX, NumericMatrix& Zstar, double& Yv1, NumericVector& WY0, bool update_state);
RcppExport SEXP _mdtm_update_counts_TwitterLDA(SEXP wSEXP, SEXP doc_usersSEXP, SEXP alphastarSEXP, SEXP bVSEXP, SEXP TOPICSSEXP, SEXP DSEXP, SEXP NSEXP, SEXP zstarSEXP, SEXP yVSEXP, SEXP WY1ZXSEXP, SEXP ZstarSEXP, SEXP Yv1SEXP, SEXP WY0SEXP, SEXP update_stateSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type w(wSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type doc_users(doc_usersSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alphastar(alphastarSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bV(bVSEXP);
    Rcpp::traits::input_parameter< int >::type TOPICS(TOPICSSEXP);
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type N(NSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type zstar(zstarSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix& >::type yV(yVSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type WY1ZX(WY1ZXSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type Zstar(ZstarSEXP);
    Rcpp::traits::input_parameter< double& >::type Yv1(Yv1SEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type WY0(WY0SEXP);
    Rcpp::traits::input_parameter< bool >::type update_state(update_stateSEXP);
    update_counts_TwitterLDA(w, doc_users, alphastar, bV, TOPICS, D, N, zstar, yV, WY1ZX, Zstar, Yv1, WY0, update_state);
    return R_NilValue;
END_RCPP
}
// update_counts_HashtagLDA
void update_counts_HashtagLDA(IntegerMatrix w, IntegerMatrix h, IntegerVector doc_users, NumericVector alphastar, NumericVector bH, int TOPICS, int D, IntegerVector N, IntegerVector L, IntegerVector& zstar, IntegerMatrix& yH, NumericMatrix& WY1ZX, NumericMatrix& HY1ZX, NumericMatrix& Zstar, double& Yh1, NumericVector& HY0, bool update_state);
RcppExport SEXP _mdtm_update_counts_HashtagLDA(SEXP wSEXP, SEXP hSEXP, SEXP doc_usersSEXP, SEXP alphastarSEXP, SEXP bHSEXP, SEXP TOPICSSEXP, SEXP DSEXP, SEXP NSEXP, SEXP LSEXP, SEXP zstarSEXP, SEXP yHSEXP, SEXP WY1ZXSEXP, SEXP HY1ZXSEXP, SEXP ZstarSEXP, SEXP Yh1SEXP, SEXP HY0SEXP, SEXP update_stateSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type w(wSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type h(hSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type doc_users(doc_usersSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alphastar(alphastarSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bH(bHSEXP);
    Rcpp::traits::input_parameter< int >::type TOPICS(TOPICSSEXP);
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type N(NSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type L(LSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type zstar(zstarSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix& >::type yH(yHSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type WY1ZX(WY1ZXSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type HY1ZX(HY1ZXSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type Zstar(ZstarSEXP);
    Rcpp::traits::input_parameter< double& >::type Yh1(Yh1SEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type HY0(HY0SEXP);
    Rcpp::traits::input_parameter< bool >::type update_state(update_stateSEXP);
    update_counts_HashtagLDA(w, h, doc_users, alphastar, bH, TOPICS, D, N, L, zstar, yH, WY1ZX, HY1ZX, Zstar, Yh1, HY0, update_state);
    return R_NilValue;
END_RCPP
}
// update_counts_MicroblogLDA
void update_counts_MicroblogLDA(std::vector<NumericMatrix>& w, IntegerVector doc_users, NumericVector alphastar, NumericVector alpha, std::vector<NumericVector>& beta, NumericMatrix b, NumericVector bdelta, NumericVector bT, double alpha0, int TOPICS, int K, int D, IntegerMatrix N, IntegerVector& x, IntegerVector& zstar, NumericMatrix& lambda, std::vector<IntegerMatrix>& y, std::vector<IntegerMatrix>& z, NumericVector& X1, NumericMatrix& Zstar, double& LAMBDA1, NumericMatrix& Z, NumericVector& Yv1, std::vector<NumericMatrix>& WY1ZX, std::vector<NumericVector>& WY0, bool update_state);
RcppExport SEXP _mdtm_update_counts_MicroblogLDA(SEXP wSEXP, SEXP doc_usersSEXP, SEXP alphastarSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP bSEXP, SEXP bdeltaSEXP, SEXP bTSEXP, SEXP alpha0SEXP, SEXP TOPICSSEXP, SEXP KSEXP, SEXP DSEXP, SEXP NSEXP, SEXP xSEXP, SEXP zstarSEXP, SEXP lambdaSEXP, SEXP ySEXP, SEXP zSEXP, SEXP X1SEXP, SEXP ZstarSEXP, SEXP LAMBDA1SEXP, SEXP ZSEXP, SEXP Yv1SEXP, SEXP WY1ZXSEXP, SEXP WY0SEXP, SEXP update_stateSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<NumericMatrix>& >::type w(wSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type doc_users(doc_usersSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alphastar(alphastarSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< std::vector<NumericVector>& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bdelta(bdeltaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bT(bTSEXP);
    Rcpp::traits::input_parameter< double >::type alpha0(alpha0SEXP);
    Rcpp::traits::input_parameter< int >::type TOPICS(TOPICSSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type N(NSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type zstar(zstarSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< std::vector<IntegerMatrix>& >::type y(ySEXP);
    Rcpp::traits::input_parameter< std::vector<IntegerMatrix>& >::type z(zSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type Zstar(ZstarSEXP);
    Rcpp::traits::input_parameter< double& >::type LAMBDA1(LAMBDA1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type Yv1(Yv1SEXP);
    Rcpp::traits::input_parameter< std::vector<NumericMatrix>& >::type WY1ZX(WY1ZXSEXP);
    Rcpp::traits::input_parameter< std::vector<NumericVector>& >::type WY0(WY0SEXP);
    Rcpp::traits::input_parameter< bool >::type update_state(update_stateSEXP);
    update_counts_MicroblogLDA(w, doc_users, alphastar, alpha, beta, b, bdelta, bT, alpha0, TOPICS, K, D, N, x, zstar, lambda, y, z, X1, Zstar, LAMBDA1, Z, Yv1, WY1ZX, WY0, update_state);
    return R_NilValue;
END_RCPP
}
// update_counts_clickbaitLDA
void update_counts_clickbaitLDA(IntegerMatrix w, IntegerVector& x, double alphastar, double betaV, NumericVector betaB, NumericVector b_doc, NumericMatrix b_back, int TOPICS, int D, int Dt, int V, IntegerVector N, IntegerVector& zstar, IntegerMatrix& yV, NumericMatrix& WY1ZX, NumericVector& Zstar, double& X1, NumericVector& Yv1, NumericMatrix& WY0, bool update_state);
RcppExport SEXP _mdtm_update_counts_clickbaitLDA(SEXP wSEXP, SEXP xSEXP, SEXP alphastarSEXP, SEXP betaVSEXP, SEXP betaBSEXP, SEXP b_docSEXP, SEXP b_backSEXP, SEXP TOPICSSEXP, SEXP DSEXP, SEXP DtSEXP, SEXP VSEXP, SEXP NSEXP, SEXP zstarSEXP, SEXP yVSEXP, SEXP WY1ZXSEXP, SEXP ZstarSEXP, SEXP X1SEXP, SEXP Yv1SEXP, SEXP WY0SEXP, SEXP update_stateSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type w(wSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type alphastar(alphastarSEXP);
    Rcpp::traits::input_parameter< double >::type betaV(betaVSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type betaB(betaBSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b_doc(b_docSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type b_back(b_backSEXP);
    Rcpp::traits::input_parameter< int >::type TOPICS(TOPICSSEXP);
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    Rcpp::traits::input_parameter< int >::type Dt(DtSEXP);
    Rcpp::traits::input_parameter< int >::type V(VSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type N(NSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type zstar(zstarSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix& >::type yV(yVSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type WY1ZX(WY1ZXSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type Zstar(ZstarSEXP);
    Rcpp::traits::input_parameter< double& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type Yv1(Yv1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type WY0(WY0SEXP);
    Rcpp::traits::input_parameter< bool >::type update_state(update_stateSEXP);
    update_counts_clickbaitLDA(w, x, alphastar, betaV, betaB, b_doc, b_back, TOPICS, D, Dt, V, N, zstar, yV, WY1ZX, Zstar, X1, Yv1, WY0, update_state);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mdtm_rcpp_CGS_HashtagLDA", (DL_FUNC) &_mdtm_rcpp_CGS_HashtagLDA, 16},
    {"_mdtm_pred_single_HashtagLDA", (DL_FUNC) &_mdtm_pred_single_HashtagLDA, 22},
    {"_mdtm_pred_all_HashtagLDA", (DL_FUNC) &_mdtm_pred_all_HashtagLDA, 22},
    {"_mdtm_rcpp_CGS_LDA", (DL_FUNC) &_mdtm_rcpp_CGS_LDA, 9},
    {"_mdtm_pred_single_LDA", (DL_FUNC) &_mdtm_pred_single_LDA, 10},
    {"_mdtm_pred_all_LDA", (DL_FUNC) &_mdtm_pred_all_LDA, 10},
    {"_mdtm_rcpp_CGS_MicroblogLDA", (DL_FUNC) &_mdtm_rcpp_CGS_MicroblogLDA, 18},
    {"_mdtm_pred_single_MicroblogLDA", (DL_FUNC) &_mdtm_pred_single_MicroblogLDA, 25},
    {"_mdtm_pred_all_MicroblogLDA", (DL_FUNC) &_mdtm_pred_all_MicroblogLDA, 25},
    {"_mdtm_rcpp_CGS_TwitterLDA", (DL_FUNC) &_mdtm_rcpp_CGS_TwitterLDA, 12},
    {"_mdtm_pred_single_TwitterLDA", (DL_FUNC) &_mdtm_pred_single_TwitterLDA, 17},
    {"_mdtm_pred_all_TwitterLDA", (DL_FUNC) &_mdtm_pred_all_TwitterLDA, 17},
    {"_mdtm_rcpp_CGS_clickbaitLDA", (DL_FUNC) &_mdtm_rcpp_CGS_clickbaitLDA, 14},
    {"_mdtm_update_counts_LDA", (DL_FUNC) &_mdtm_update_counts_LDA, 9},
    {"_mdtm_update_counts_TwitterLDA", (DL_FUNC) &_mdtm_update_counts_TwitterLDA, 14},
    {"_mdtm_update_counts_HashtagLDA", (DL_FUNC) &_mdtm_update_counts_HashtagLDA, 17},
    {"_mdtm_update_counts_MicroblogLDA", (DL_FUNC) &_mdtm_update_counts_MicroblogLDA, 26},
    {"_mdtm_update_counts_clickbaitLDA", (DL_FUNC) &_mdtm_update_counts_clickbaitLDA, 20},
    {NULL, NULL, 0}
};

RcppExport void R_init_mdtm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
