# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_CGS_HashtagLDA <- function(w, h, doc_users, alphastar, betaV, betaH, bH, iterations, TOPICS, U, D, V, H, N, L, L_sum, Lmax, betaV_sum, betaH_sum, result_folder) {
    invisible(.Call(`_mdtm_rcpp_CGS_HashtagLDA`, w, h, doc_users, alphastar, betaV, betaH, bH, iterations, TOPICS, U, D, V, H, N, L, L_sum, Lmax, betaV_sum, betaH_sum, result_folder))
}

rcpp_CGS_LDA <- function(w, alpha, betaV, iterations, TOPICS, D, V, N, Nmax, betaV_sum, result_folder) {
    invisible(.Call(`_mdtm_rcpp_CGS_LDA`, w, alpha, betaV, iterations, TOPICS, D, V, N, Nmax, betaV_sum, result_folder))
}

rcpp_CGS_MicroblogLDA <- function(w, doc_users, alphastar, alpha, beta, b, bdelta, bT, alpha0, iterations, TOPICS, K, U, D, V, N, N_sum, Nmax, beta_sum, Dusers, result_folder) {
    invisible(.Call(`_mdtm_rcpp_CGS_MicroblogLDA`, w, doc_users, alphastar, alpha, beta, b, bdelta, bT, alpha0, iterations, TOPICS, K, U, D, V, N, N_sum, Nmax, beta_sum, Dusers, result_folder))
}

rcpp_CGS_TwitterLDA <- function(w, doc_users, alphastar, betaV, bV, iterations, TOPICS, U, D, V, N, N_sum, Nmax, betaV_sum, result_folder) {
    invisible(.Call(`_mdtm_rcpp_CGS_TwitterLDA`, w, doc_users, alphastar, betaV, bV, iterations, TOPICS, U, D, V, N, N_sum, Nmax, betaV_sum, result_folder))
}

