# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_CGS_HashtagLDA <- function(w, h, doc_users, alphastar, betaV, betaH, bH, iterations, TOPICS, U, D, V, H, N, L, result_folder) {
    invisible(.Call(`_mdtm_rcpp_CGS_HashtagLDA`, w, h, doc_users, alphastar, betaV, betaH, bH, iterations, TOPICS, U, D, V, H, N, L, result_folder))
}

pred_single_HashtagLDA <- function(w, h, doc_users, alphastar, betaV, betaH, bH, iterations, TOPICS, U, D, V, H, N, L, L_sum, WY1ZX, HY1ZX, Zstar, Yh1, HY0, result_folder) {
    invisible(.Call(`_mdtm_pred_single_HashtagLDA`, w, h, doc_users, alphastar, betaV, betaH, bH, iterations, TOPICS, U, D, V, H, N, L, L_sum, WY1ZX, HY1ZX, Zstar, Yh1, HY0, result_folder))
}

pred_all_HashtagLDA <- function(w, h, doc_users, alphastar, betaV, betaH, bH, iterations, TOPICS, U, D, V, H, N, L, L_sum, WY1ZX, HY1ZX, Zstar, Yh1, HY0, result_folder) {
    invisible(.Call(`_mdtm_pred_all_HashtagLDA`, w, h, doc_users, alphastar, betaV, betaH, bH, iterations, TOPICS, U, D, V, H, N, L, L_sum, WY1ZX, HY1ZX, Zstar, Yh1, HY0, result_folder))
}

rcpp_CGS_LDA <- function(w, alpha, betaV, iterations, TOPICS, D, V, N, result_folder) {
    invisible(.Call(`_mdtm_rcpp_CGS_LDA`, w, alpha, betaV, iterations, TOPICS, D, V, N, result_folder))
}

pred_single_LDA <- function(w, alpha, betaV, iterations, TOPICS, D, V, N, WY1ZX, result_folder) {
    invisible(.Call(`_mdtm_pred_single_LDA`, w, alpha, betaV, iterations, TOPICS, D, V, N, WY1ZX, result_folder))
}

pred_all_LDA <- function(w, alpha, betaV, iterations, TOPICS, D, V, N, WY1ZX, result_folder) {
    invisible(.Call(`_mdtm_pred_all_LDA`, w, alpha, betaV, iterations, TOPICS, D, V, N, WY1ZX, result_folder))
}

rcpp_CGS_MicroblogLDA <- function(w, doc_users, alphastar, alpha, beta, b, bdelta, bT, alpha0, iterations, TOPICS, K, U, D, V, N, Dusers, result_folder) {
    invisible(.Call(`_mdtm_rcpp_CGS_MicroblogLDA`, w, doc_users, alphastar, alpha, beta, b, bdelta, bT, alpha0, iterations, TOPICS, K, U, D, V, N, Dusers, result_folder))
}

pred_single_MicroblogLDA <- function(w, doc_users, alphastar, alpha, beta, b, bdelta, bT, alpha0, iterations, TOPICS, K, U, D, V, N, N_sum, Dusers, X1, Zstar, LAMBDA1, Yv1, WY1ZX, WY0, result_folder) {
    invisible(.Call(`_mdtm_pred_single_MicroblogLDA`, w, doc_users, alphastar, alpha, beta, b, bdelta, bT, alpha0, iterations, TOPICS, K, U, D, V, N, N_sum, Dusers, X1, Zstar, LAMBDA1, Yv1, WY1ZX, WY0, result_folder))
}

pred_all_MicroblogLDA <- function(w, doc_users, alphastar, alpha, beta, b, bdelta, bT, alpha0, iterations, TOPICS, K, U, D, V, N, N_sum, Dusers, X1, Zstar, LAMBDA1, Yv1, WY1ZX, WY0, result_folder) {
    invisible(.Call(`_mdtm_pred_all_MicroblogLDA`, w, doc_users, alphastar, alpha, beta, b, bdelta, bT, alpha0, iterations, TOPICS, K, U, D, V, N, N_sum, Dusers, X1, Zstar, LAMBDA1, Yv1, WY1ZX, WY0, result_folder))
}

rcpp_CGS_TwitterLDA <- function(w, doc_users, alphastar, betaV, bV, iterations, TOPICS, U, D, V, N, result_folder) {
    invisible(.Call(`_mdtm_rcpp_CGS_TwitterLDA`, w, doc_users, alphastar, betaV, bV, iterations, TOPICS, U, D, V, N, result_folder))
}

pred_single_TwitterLDA <- function(w, doc_users, alphastar, betaV, bV, iterations, TOPICS, U, D, V, N, N_sum, WY1ZX, Zstar, Yv1, WY0, result_folder) {
    invisible(.Call(`_mdtm_pred_single_TwitterLDA`, w, doc_users, alphastar, betaV, bV, iterations, TOPICS, U, D, V, N, N_sum, WY1ZX, Zstar, Yv1, WY0, result_folder))
}

pred_all_TwitterLDA <- function(w, doc_users, alphastar, betaV, bV, iterations, TOPICS, U, D, V, N, N_sum, WY1ZX, Zstar, Yv1, WY0, result_folder) {
    invisible(.Call(`_mdtm_pred_all_TwitterLDA`, w, doc_users, alphastar, betaV, bV, iterations, TOPICS, U, D, V, N, N_sum, WY1ZX, Zstar, Yv1, WY0, result_folder))
}

rcpp_CGS_clickbaitLDA <- function(w, x, alphastar, betaV, betaB, b_doc, b_back, iterations, TOPICS, D, Dt, V, N, result_folder) {
    invisible(.Call(`_mdtm_rcpp_CGS_clickbaitLDA`, w, x, alphastar, betaV, betaB, b_doc, b_back, iterations, TOPICS, D, Dt, V, N, result_folder))
}

update_counts_LDA <- function(w, alpha, TOPICS, D, N, zV, WY1ZX, Z, update_state) {
    invisible(.Call(`_mdtm_update_counts_LDA`, w, alpha, TOPICS, D, N, zV, WY1ZX, Z, update_state))
}

update_counts_TwitterLDA <- function(w, doc_users, alphastar, bV, TOPICS, D, N, zstar, yV, WY1ZX, Zstar, Yv1, WY0, update_state) {
    invisible(.Call(`_mdtm_update_counts_TwitterLDA`, w, doc_users, alphastar, bV, TOPICS, D, N, zstar, yV, WY1ZX, Zstar, Yv1, WY0, update_state))
}

update_counts_HashtagLDA <- function(w, h, doc_users, alphastar, bH, TOPICS, D, N, L, zstar, yH, WY1ZX, HY1ZX, Zstar, Yh1, HY0, update_state) {
    invisible(.Call(`_mdtm_update_counts_HashtagLDA`, w, h, doc_users, alphastar, bH, TOPICS, D, N, L, zstar, yH, WY1ZX, HY1ZX, Zstar, Yh1, HY0, update_state))
}

update_counts_MicroblogLDA <- function(w, doc_users, alphastar, alpha, beta, b, bdelta, bT, alpha0, TOPICS, K, D, N, x, zstar, lambda, y, z, X1, Zstar, LAMBDA1, Z, Yv1, WY1ZX, WY0, update_state) {
    invisible(.Call(`_mdtm_update_counts_MicroblogLDA`, w, doc_users, alphastar, alpha, beta, b, bdelta, bT, alpha0, TOPICS, K, D, N, x, zstar, lambda, y, z, X1, Zstar, LAMBDA1, Z, Yv1, WY1ZX, WY0, update_state))
}

update_counts_clickbaitLDA <- function(w, x, alphastar, betaV, betaB, b_doc, b_back, TOPICS, D, Dt, V, N, zstar, yV, WY1ZX, Zstar, X1, Yv1, WY0, update_state) {
    invisible(.Call(`_mdtm_update_counts_clickbaitLDA`, w, x, alphastar, betaV, betaB, b_doc, b_back, TOPICS, D, Dt, V, N, zstar, yV, WY1ZX, Zstar, X1, Yv1, WY0, update_state))
}

